### PR TITLE
Schema version mismatch detected in Kubernetes Cluster #168

### LINKED ISSUE #168: Schema version mismatch detected in Kubernetes Cluster
Hi ecAudit Team,

We are using Cassandra 3.11.9 and ecAduit 2.6.0 with Role based whitelist. We are deploying cassandra in Kubernetes cluster and in 'docker-entrypoint' script on pod-1, when we alter 'system_auth' replication factor to 2 using 'cassandra' super user then we got below error:

`<stdin>:1:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
<stdin>:1:Schema metadata was not refreshed. See log for details.
Connection error: ('Unable to connect to any servers', {'192.168.131.17': AuthenticationFailed('Failed to authenticate to 192.
168.131.17: Error from server: code=0100 [Bad credentials] message="Provided username admin and/or password are incorrect"',)})`

If we deploy Cassandra without ecAudit, then it works fine.

Based on our analysis, we found that when we altered 'system_auth' keyspace replication factor, ecAudit tried to audit this record and goes to find the whitelist user for this alter statement (Though ecAudit cached these roles but still it hits database). This is where it's not able to get the whitelist role using 'cassandra' super user as it tried with CL.QUORUM for 'cassandra' user but only pod-0 is up when docker-entrypoint executes on pod-1.

So, what we thought if there is an exception when getting whitelist user, we will not audit a record when there is an exception while fetching whitelist roles from database.

### PR DESCRIPTION
**Pull request by pushpendra-rajpoot**
Audit a record even if there is an exception while fetching whitelist role from table.

Fixes #168

### CODE REVIEW

**Review by pushpendra-rajpoot — COMMENTED** [review]
Reset POM

File: ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java [hunk 1]
```diff
@@ -79,6 +79,9 @@ private boolean shouldAudit(AuditEntry logEntry)
         {
             return !filter.isWhitelisted(logEntry);
         }
+        catch(Exception ex) {
+        	return false;
```
Comment (etedpet) [inline ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java:83]: I think this should be the other way around - return true in this case.
If we cannot find any whitelist-info, the we assume that "whitelisting" is false -> meaning that shouldAudit() should return true.

**Review by etedpet — CHANGES_REQUESTED** [review]
I think the new logic should be inverted

**Review by pushpendra-rajpoot — COMMENTED** [review]
Return statement updated. Also, changed jar version to 2.7.1

**Review by eperott — CHANGES_REQUESTED** [review]
Thanks for the PR!

Please add line to comment with reference to the Issue you created. For tracking..

**Comment by eperott** [comment]
You need to update version in all pom files.

Also, your commit message no longer matches your fix.

**Review by pushpendra-rajpoot — COMMENTED** [review]
Updated jar version

**Review by pushpendra-rajpoot — COMMENTED** [review]
Updated patch version

File: ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java [hunk 2]
```diff
@@ -79,6 +79,9 @@ private boolean shouldAudit(AuditEntry logEntry)
         {
             return !filter.isWhitelisted(logEntry);
         }
+        catch(Exception ex) {
```
Comment (etedpet) [inline ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java:82]: Everywhere else in the code, Exception variables are called "e"
Please update that to be consistent

File: ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java [hunk 3]
```diff
@@ -109,6 +110,7 @@ public void testAuditFiltered()
         assertThat(timeMeasured).isLessThanOrEqualTo(timeTaken);
     }
 
+    @Ignore
```
Comment (etedpet) [inline ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java:113]: Update this test case instead of ignoring it. Make sure that an entry is logged when this happens...

Also - if the test-method:
  timedOperation(Runnable runnable, Class<? extends Exception> expectedExceptionClass)
is no longer used, remove it.

**Review by etedpet — COMMENTED** [review]
Make sure tests are covering the new logic

**Review by pushpendra-rajpoot — COMMENTED** [review]
Updated as per comments

File: ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java [hunk 4]
```diff
@@ -109,22 +109,6 @@ public void testAuditFiltered()
         assertThat(timeMeasured).isLessThanOrEqualTo(timeTaken);
     }
```
Comment (etedpet) [inline ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java:111]: This test (testAuditFilteredThrowsException()) should be updated - not removed

To assert that even though an exceptions is thrown, the the audit-method does the correct thing (the new/updated logic).

So this test case should look very similar to testAuditNotFiltered(), except that mockFilter.isWhitelisted() should throw the exception (same as today - line 116)

**Review by etedpet — APPROVED** [review]
Update/fix the test case instead of removing it

**Comment by pushpendra-rajpoot** [comment]
Hi ecaudit team, I updated the test case as per your instruction.

File: ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java [hunk 5]
```diff
@@ -114,14 +114,16 @@ public void testAuditFilteredThrowsException()
     {
         AuditEntry logEntry = AuditEntry.newBuilder().build();
         when(mockFilter.isWhitelisted(logEntry)).thenThrow(new ReadTimeoutException(ConsistencyLevel.QUORUM, 1, 1, false));
+        when(mockObfuscator.obfuscate(logEntry)).thenReturn(logEntry);
```
Comment (etedpet) [inline ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java:117]: The name of this test case should be updated - testAuditFilteredThrowsException()
It now handles the exception... So maybe call the method "testAuditFilteredHandlesException" or something similar...

**Review by etedpet — CHANGES_REQUESTED** [review]
Update the test case name to match the new (expected) behavior.

File: ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java (hunk 5 above)
Comment (pushpendra-rajpoot) [reply ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java:117]: Updated method name

**Review by pushpendra-rajpoot — COMMENTED** [review]
Fix #168

File: ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java [hunk 6]
```diff
@@ -79,6 +79,9 @@ private boolean shouldAudit(AuditEntry logEntry)
         {
             return !filter.isWhitelisted(logEntry);
         }
+        catch(Exception e) {
+        	return true;
```
Comment (eperott) [inline ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java:83]: This solves the immediat issue during start-up. But it will also hide faults in the system long after start-up (potentially causing audits to flod your logs) without giving any trace of the error for the operator.

Would it make sense to narrow it down a bit (UnavailableException?) and perhaps do this in the RoleAuditFilter where the issue originating from? Should we log an error for troubleshooting (and remove call to addSuppressed() until the logback issue is resolved)?

Would it make sense to explore the option of always waiting for schema agreement during start-up. In other words should we remove this condition:
https://github.com/Ericsson/ecaudit/blob/release/c2.2/ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistDataAccess.java#L234

WDYT?
